#!/bin/sh
#
# Script name: bb_IDP_SWI_T2star
#
# Description: Script to generate the IDPs related to swMRI.
#
# Authors: Fidel Alfaro-Almagro, Stephen M. Smith & Mark Jenkinson
#
# Copyright 2017 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

origDir=`pwd`
scriptName=`basename "$0"`
direc=$1

cd $direc

baseT1="T1"
#if [ -d T1/unusable ] ; then
#    baseT1="T1/unusable"
#fi

baseSWI="SWI"
#if [ -d $baseSWI/unusable ] ; then
#    baseSWI="$baseSWI/unusable"
#fi

#Setting the string of NaN in case there is a problem.
numVars="14"
result="";
for i in $(seq 1 $numVars) ; do 
    result="NaN $result" ; 
done 

# Extract line numbers where the second column contains "lh" or "rh"
lh_rh_lines=$(awk -F'\t' '$2 ~ /lh|rh/ {print NR}' $PARC_LUT)

if [ -f $baseSWI/T2star_to_T1.nii.gz ] ; then
  if [ -f $baseT1/T1_first/T1_first_all_fast_firstseg.nii.gz ] ; then
    vals=`fslstats -K $baseT1/T1_first/T1_first_all_fast_firstseg $baseSWI/T2star_to_T1 -p 50 `
    
    # Generate the dynamic print command based on the selected line numbers
    awk_command=''
    # Start building the awk command
    awk_command='awk '\''{print'
    
    # Add the desired fields to the print statement
    for line in $lh_rh_lines; do
        awk_command="$awk_command \$$line \" \""
    done
    
    # Close the print statement and the awk command
    awk_command="${awk_command}}'"
    
    # Execute the command using eval
    result=$(echo $vals | eval $awk_command)
    
  fi
fi

mkdir -p IDP_files

echo $result > IDP_files/$scriptName.txt
echo $result

cd $origDir

