blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki
    about: Official tvb-ukbb documentation
  - name: ❓ FAQ
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki/FAQ
    about: Frequently Asked Questions
  - name: 💬 Questions & Discussion
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions
    about: Discussions Board
  - name: 💡 Feature Requests
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions/new/choose
    about: tvb-ukbb missing something? Let us know.
  - name: 🛠️ Support Requests
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions/new/choose
    about: Something not working? Having trouble with installation or processing? Head to our Discussions Page.
